const CartActionTypes = {
    ADD_ITEMS_TO_CART : "ADD_ITEMS_TO_CART",
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN",
    INCREASE_ITEM : "INCREASE_ITEM",
    DECREASE_ITEM : "DECREASE_ITEM",
    REMOVE_ITEM : "REMOVE_ITEM"
}
export default CartActionTypes;